-- MySQL Script generated by MySQL Workbench
-- Mon May 17 11:51:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `roomNo` INT NOT NULL AUTO_INCREMENT,
  `roomName` VARCHAR(45) NULL,
  `area` FLOAT NULL,
  `category` VARCHAR(45) NULL,
  `pricePerUnit` DECIMAL NULL,
  `lastUpdate` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`roomNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `empNo` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`empNo`),
  UNIQUE INDEX `empNo_UNIQUE` (`empNo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ContactData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ContactData` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `streetNo` VARCHAR(10) NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `mail` VARCHAR(80) NULL,
  `lastUpdate` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`addressId`),
  UNIQUE INDEX `addressId_UNIQUE` (`addressId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `addressId` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `ContactData_addressId` INT NOT NULL,
  `lastUpdate` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`custId`),
  UNIQUE INDEX `custId_UNIQUE` (`custId` ASC),
  INDEX `fk_Customer_ContactData_idx` (`ContactData_addressId` ASC),
  CONSTRAINT `fk_Customer_ContactData`
    FOREIGN KEY (`ContactData_addressId`)
    REFERENCES `mydb`.`ContactData` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `bookingId` INT NOT NULL AUTO_INCREMENT,
  `bookingDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `empNo` INT NOT NULL,
  `custId` INT NOT NULL,
  `roomNo` INT NOT NULL,
  `dateframe` DATE NULL,
  `timeframe` VARCHAR(45) NULL,
  `specialWishes` VARCHAR(100) NULL,
  `Employee_empNo` INT NOT NULL,
  `Customer_custId` INT NOT NULL,
  PRIMARY KEY (`bookingId`),
  UNIQUE INDEX `bookingId_UNIQUE` (`bookingId` ASC),
  INDEX `fk_Booking_Employee1_idx` (`Employee_empNo` ASC),
  INDEX `fk_Booking_Customer1_idx` (`Customer_custId` ASC),
  CONSTRAINT `fk_Booking_Employee1`
    FOREIGN KEY (`Employee_empNo`)
    REFERENCES `mydb`.`Employee` (`empNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Customer1`
    FOREIGN KEY (`Customer_custId`)
    REFERENCES `mydb`.`Customer` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookingRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookingRequest` (
  `reqId` INT NOT NULL AUTO_INCREMENT,
  `bookingRequestDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `custId` INT NOT NULL,
  `roomNo` INT NOT NULL,
  `amountPeople` INT NOT NULL,
  `price` DECIMAL NULL,
  `Customer_custId` INT NOT NULL,
  `Room_roomNo` INT NOT NULL,
  PRIMARY KEY (`reqId`),
  UNIQUE INDEX `reqId_UNIQUE` (`reqId` ASC),
  INDEX `fk_BookingRequest_Customer1_idx` (`Customer_custId` ASC),
  INDEX `fk_BookingRequest_Room1_idx` (`Room_roomNo` ASC),
  CONSTRAINT `fk_BookingRequest_Customer1`
    FOREIGN KEY (`Customer_custId`)
    REFERENCES `mydb`.`Customer` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookingRequest_Room1`
    FOREIGN KEY (`Room_roomNo`)
    REFERENCES `mydb`.`Room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room_has_Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room_has_Booking` (
  `Room_roomNo` INT NOT NULL,
  `Booking_bookingId` INT NOT NULL,
  PRIMARY KEY (`Room_roomNo`, `Booking_bookingId`),
  INDEX `fk_Room_has_Booking_Booking1_idx` (`Booking_bookingId` ASC),
  INDEX `fk_Room_has_Booking_Room1_idx` (`Room_roomNo` ASC),
  CONSTRAINT `fk_Room_has_Booking_Room1`
    FOREIGN KEY (`Room_roomNo`)
    REFERENCES `mydb`.`Room` (`roomNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Room_has_Booking_Booking1`
    FOREIGN KEY (`Booking_bookingId`)
    REFERENCES `mydb`.`Booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
